version: '3'
services:
  cassandra:
    image: "datastax/dse-server:6.8.14"
    environment:
      - DS_LICENSE=accept
    cap_add:
    - IPC_LOCK
    ulimits:
      memlock: -1
#  node:
#    image: "datastax/dse-server"
#    environment:
#      - DS_LICENSE=accept
#      - SEEDS=seed_node
#    links:
#      - seed_node
#    cap_add:
#    - IPC_LOCK
#    ulimits:
#      memlock: -1
  studio:
    image: "datastax/dse-studio"
    environment:
      - DS_LICENSE=accept
    ports:
      - 9091:9091
